matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.3"
    - os: linux
      python: "3.4"
    - os: linux
      python: "3.5"
    - os: linux
      python: "3.6"


script:
    - which python && python --version && cd tools/creator/tests && python ./main.py

