language: python

matrix:
  include:
    - language: generic
      os: osx
    - python: 2.7
      os: linux
    - python: 3.3
      os: linux
    - python: 3.4
      os: linux
    - python: 3.5
      os: linux
    - python: 3.6
      os: linux


script:
    - bash ./.travis/run.sh

